### ISSUE TITLE
Error with ng build --prod

### ISSUE THREAD

**Issue by Otakug3** [masvis/angular4-hal#10]
Hi again, after solving #9 I'm trying to execute again "ng build --prod" and gives me this error:

>ERROR in ./node_modules/angular4-hal/index.ts
Module build failed: Error: \node_modules\angular4-hal\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)

>ERROR in ./node_modules/angular4-hal/src/external.service.ts
Module build failed: Error:\node_modules\angular4-hal\src\external.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)

>ERROR in ./node_modules/angular4-hal/src/resource.service.ts
Module build failed: Error: \node_modules\angular4-hal\src\resource.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile \node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then \node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)

I checked the src folder and there isn't any of the files that give me the error and after some digging I found this #[github.com/ng-cli#8284](https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325) and I think that I'm on the right track but not able to resolve it. 

This is due a bad packaging? Because if I clone the project and try to compile by myself every .js is there normally... Thank you for your effort

**Comment by Otakug3** [comment]
Thanks again for your work but this update don't fix the problem for why I opened this issue. It's still complaining about the .ts and bad packaging, and failing when I'm trying to compile. On the other hand, If i delete the .ts that give me problems, my typescript doesn't find the functions of the library like, getAll(), getRelationArray(), etc...

**Comment by sante85** [comment]
update to 4.x

**Comment by Otakug3** [comment]
I'm following your changes and my last message was about 4.3.1 version.

**Comment by sante85** [comment]
please get an running example, o plunker

**Comment by Otakug3** [comment]
It's the same problem that #12 said, I'm working on a running example to show you

**Comment by Otakug3** [comment]
I have it already, now it's not failing when you do "ng build --prod" but the same error appears when you do "ng serve" so I supose that it will be the same problem 
[hal-fails.zip](https://github.com/masvis/angular4-hal/files/1875129/hal-fails.zip)

**Comment by sante85** [comment]
https://github.com/dherges/ng-packagr/issues/727

"build": "ng build --prod --aot=false",

Is resolved

**Comment by Otakug3** [comment]
I really need AOT activated so please I can accept this workaround for now but please let the issue opened for the guys of ng-packagr issue that you referenced here they would see that the status is still pending.

Thanks.

**Comment by sante85** [comment]
my library work right. this is solution, contact angular team

**Comment by rogargon** [comment]
Also experiencing the problem with AOT when running "ng serve -aot" or "ng build --prod". The error is:

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'AngularHalModule' was called.

Using: "angular4-hal": "^4.5.1" 

The problem is with the line in app.module.ts imports: 
...
AngularHalModule.forRoot(),
...

It disappears if I comment it out. Though, obviously, the application later crashes because it cannot find AngularHal.

The reason might be pointed out in the following example: https://github.com/jeffora/ng-barrel

**Comment by sante85** [comment]
dherges/ng-packagr#727

"build": "ng build --prod --aot=false",

Is resolved

**Comment by rogargon** [comment]
Sorry, your solution is just a workaround that disables AOT and thus
hampers the performance of any application that includes Angular4-HAL:

https://blog.nrwl.io/angular-is-aot-worth-it-8fa02eaf64d4
-- 
Roberto García
http://rhizomik.net/~roberto
