### ISSUE TITLE
Error on building ng -serve  version 4.3.3

### ISSUE THREAD

**Issue by eidos71** [masvis/angular4-hal#12]
Greetings!.

Setting the latest version 4.3.3 I found the following build error.

Version 4.3.3
``
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-03-31T15:47:43.728Z
Hash: ca093c63a080102267d0
Time: 8658ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 211 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 557 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 634 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 13.4 MB [initial] [rendered]

ERROR in ./node_modules/angular4-hal/index.ts
Module build failed: Error: /home/blackswan/git/transit-client/transti-hub-client/node_modules/angular4-hal/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/blackswan/git/transit-client/transti-hub-client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/home/blackswan/git/transit-client/transti-hub-client/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

webpack: Failed to compile.

**Comment by sante85** [comment]
in tsconfig.app.json
add
{
  "extends": "../tsconfig.json",
....
"include":[
    "./**/*.ts",
    "../node_modules/angular4-hal/**/*.ts"
  ]
}
in main object

**Comment by sante85** [comment]
"../node_modules/angular4-hal/**/*.ts"

**Comment by sante85** [comment]
"./**/*.ts",
