### ISSUE TITLE
Add custom header

### ISSUE THREAD

**Issue by mpbalmeida** [masvis/angular4-hal#14]
Is there any way i can set a custom header like Authorization?

**Comment by mpbalmeida** [comment]
I resolved it using a HttpInterceptor
`@Injectable()
export class AuthInterceptor implements HttpInterceptor {

  constructor(private userInfoService: UserInfoService) { }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    let token = this.userInfoService.getStoredToken();
    let customReq;
    // add a custom header
    if (token !== null) {
      customReq = request.clone({
        headers: request.headers.set('Authorization', 'Bearer ' + token)
      });
    } else {
      let clientId: string = environment.clientId;
      let clientSecret: string = environment.clientSecret;

      let headerAuthorizationPlain: string = clientId + ':' + clientSecret;
      let btoaAuth = btoa(headerAuthorizationPlain);
      customReq = request.clone({
        headers: request.headers.set('Authorization', 'Basic ' + btoaAuth)
      });
    }

    // pass on the modified request object
    return next.handle(customReq);
  }


}`

**Comment by sante85** [comment]
ResourceHelper.headers = .....
