### ISSUE TITLE
Error using addRelation

### ISSUE THREAD

**Issue by Otakug3** [masvis/angular4-hal#15]
The error that gives me it's this:

ERROR TypeError: Cannot read property 'append' of undefined
    at MyObjectHal.Resource.addRelation (resource.ts:64)

I don't see where is the headers field being initialized and this is where is giving me the null

**Comment by sante85** [comment]
You can do ResourceHelper.headers = ....

**Comment by Otakug3** [comment]
Oh, I see!

Anyway, can you initialize it by default in the same way that you do with http? If I don't want to use any header I shouldn't initialize it only because library uses it.

It's good to have a setter if I want to change it but not to be forced to do it by myself or it doesnt work.

Thanks.

**Comment by sante85** [comment]
update version 4.5.0
