### ISSUE TITLE
Errors when using `getRelation` or `getRelationArray` when `_link` key does not exist

### ISSUE THREAD

**Issue by jamsuu** [masvis/angular4-hal#18]
`getRelation` and `getRelationArray` both check that `_links` is defined, but do not check that the relational key is also defined. This is a problem if you're using subtypes for your classes that may/may not have the relational links. 

Eg. I have a bunch of subtypes for a `Server`. Some of these subtypes have a relationship to a `Cluster`, some have a relationship to `Region`, but never both.

**Comment by sante85** [comment]
fixed
