### ISSUE TITLE
Any plans to provide a way to handle serialization/deserialization of objects?

### ISSUE THREAD

**Issue by jamsuu** [masvis/angular4-hal#19]
Loving the library, but would love it even more if there was a way to provide a custom way to handle serialization/deserialization of entities. I'm currently using [json-object-mapper](https://www.npmjs.com/package/json-object-mapper) in other projects of mine to convert objects (such as dates returned downstream as an ISO string into a JS Date, and back to ISO string when posting upstream). `ResourceService` currently has a hard dependency on `ResourceHelper`'s static methods and makes it difficult to provide any custom serialize/deserialize capabilities.

**Comment by sante85** [comment]
This is a possible enhancement, but a litte aim is preferable to continue development. 

https://www.paypal.com/webapps/shoppingcart?flowlogging_id=29f6212ee079c&mfid=1525777002269_29f6212ee079c#/checkout/openButton

Thanks
