### ISSUE TITLE
angular4-hal example

### ISSUE THREAD

**Issue by alexvw** [masvis/angular4-hal#2]
Hi - Do you have an example of angular4-hal within a working application? This library seems to do exactly what we need, but I am having some issues that I think looking at a working example would resolve. Thanks

**Comment by sante85** [comment]
what is your problem?

**Comment by alexvw** [comment]
I have had a few issues getting it to build AOT (same as the other user just posted), but your latest update fixed some of them. Right now, I have two different issues with external.service.ts. 

Trying to provide APP_URI like you have in your readme throws an error:
...
{ provide: API_URI, useValue: 'localhost:8081/mockrp2/api' },
    { provide: PROXY_URI, useValue: '' },
...
[ERROR]   Function calls are not supported in decorators but 'InjectionToken' was called in 'API_URI'

If I try to remove this just to see if it will build, it still doesn't like the injection external.service.ts:

[INFO] $ ng build -prod --output-path dist/META-INF/resources/webjars/mockrp2-frontend
[ERROR] Failed on type {"filePath":"C:/idw-dev/idw-mockrp-oidc/frontend/node_modules/angular4-hal/src/external.service.ts","name":"ExternalService","members":[]} with error Error: angular4-hal/src/external.service.ts(11,18): Error during template compile of 'ExternalService'
[ERROR]   Function expressions are not supported in decorators in 'Inject'
[ERROR]     'Inject' contains the error at @angular/core/core.ts(61,69)
[ERROR]       Consider changing the function expression into an exported function.
[INFO] Date: 2018-01-17T19:14:40.664Z

**Comment by sante85** [comment]
[hal-test.zip](https://github.com/masvis/angular4-hal/files/1642252/hal-test.zip)
this is an example

**Comment by Sleeper9** [comment]
@alexvw The latest version fixed that problem for me as you wrote (I have others besides that... :disappointed: ). Maybe try to delete node_modules/angular4-hal folder and reinstall?

**Comment by karqu** [comment]
I downloaded now this problem, I:

npm install
ng serve

And I have same error:

ERROR Error: StaticInjectorError[InjectionToken DocumentToken]: 
  StaticInjectorError[InjectionToken DocumentToken]: 
    NullInjectorError: No provider for InjectionToken DocumentToken!
    at _NullInjector.get (core.js:993)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveToken (core.js:1281)
    at tryResolveToken (core.js:1223)
    at StaticInjector.get (core.js:1094)
    at resolveNgModuleDep (core.js:10878)
    at _createClass (core.js:10919)
    at _createProviderInstance$1
