### ISSUE TITLE
Angular 6, rxjs 6 support

### ISSUE THREAD

**Issue by ghost** [masvis/angular4-hal#20]
When will it be compatible with angular 6 and rxjs 6 ?

**Comment by Otakug3** [comment]
I'm interested in this too. It's quite easy, you only have to follow the steps of this update.angular.io and replace some syntax.

**Comment by Otakug3** [comment]
I'm interested in this too. It's quite easy, you only have to follow the steps of this http://update.angular.io and replace some syntax.

**Comment by chesteric31** [comment]
+1
