### ISSUE TITLE
No provider for InjectionToken DocumentToken!

### ISSUE THREAD

**Issue by Sleeper9** [masvis/angular4-hal#3]
When trying to use the library, it gives me the following message right when I hit a page that uses a HAL-enabled service:

```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
  StaticInjectorError(Platform: core)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
    NullInjectorError: No provider for InjectionToken DocumentToken!
Error: StaticInjectorError(AppModule)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
  StaticInjectorError(Platform: core)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
    NullInjectorError: No provider for InjectionToken DocumentToken!
    at _NullInjector.get (core.js:994)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveNgModuleDep (core.js:10836)
    at _createClass (core.js:10877)
    at _createProviderInstance$1 (core.js:10847)
    at _NullInjector.get (core.js:994)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveToken (core.js:1292)
    at tryResolveToken (core.js:1234)
    at StaticInjector.get (core.js:1102)
    at resolveNgModuleDep (core.js:10836)
    at _createClass (core.js:10877)
    at _createProviderInstance$1 (core.js:10847)
    at resolvePromise (zone.js:809)
    at resolvePromise (zone.js:775)
    at eval (zone.js:858)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4724)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1517)
```

**Comment by Sleeper9** [comment]
Sorry, I think this issue still persists in 1.8.6. Can you look at it? [This SO question](https://stackoverflow.com/questions/48174555/angular-cant-use-httpclient-in-external-library) and [this github issue](https://github.com/angular/angular/issues/21426) seem to related, maybe it's a problem with the library packaging?

**Comment by sante85** [comment]
if you want get http client simply

@Injectable()
export class AuthService extends RestService<Auth> {

constructor(private externalService: ExternalService, injector: Injector) {
    super(Auth, "", injector);
  }

..................

this.externalService.getHttp()

**Comment by sante85** [comment]
what is your question?

**Comment by Sleeper9** [comment]
Thanks, I am able to access httpClient this way, so I removed the HttpClient injection from constructors and removed HttpClient from app.module providers and imports as well, but the problem still exists. I did everything as it's written in README.md, I just can't see what I am missing...

**Comment by sante85** [comment]
please post your code entirely or post a plunker

**Comment by Sleeper9** [comment]
Please see [this comment](https://github.com/angular/angular/issues/21426#issuecomment-356999358), this is exactly what I had to do to get it working (that's not a real solution though, because it redownloads node_modules directory again on an `npm install`)

**Comment by Sleeper9** [comment]
app.module.ts

```
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {AppRoutingModule} from './app-routing.module';

import {AngularHalModule, PROXY_URI, API_URI} from 'angular4-hal';

import {environment} from '../environments/environment';

import {AppComponent} from './app.component';
import {ProjectListComponent} from './projects/project-list.component';

import {DateService} from './services/date.service';
import {ProjectService} from './services/project.service';

@NgModule({
  declarations: [
    AppComponent,
    ProjectListComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AngularHalModule.forRoot(),
    FormsModule,
    ReactiveFormsModule,
    AppRoutingModule
  ],
  providers: [
    { provide: API_URI, useValue: environment.api_url },
    { provide: PROXY_URI, useValue: '' },
    DateService,
    ProjectService
   ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

project.service.ts
```
import {Injectable, Injector} from '@angular/core';
import Project from '../models/project.model';
import {RestService, ExternalService} from 'angular4-hal';
import {Observable} from 'rxjs/Observable';

@Injectable()
export class ProjectService extends RestService<Project> {

  constructor(private externalService: ExternalService, injector: Injector) {
    super(Project, 'projects', injector);
  }

  getAll(): Observable<Project[]>  {
    return super.getAll();
  }

  save(data) {
    return this.externalService.getHttp().post(`api/projects`, data);
  }
}
```

project.model.ts
```
import {Resource} from 'angular4-hal';
import {DateService} from '../services/date.service';

export default class Project extends Resource {
  interval: {
    beginDate: any;
    endDate: any;
  };
  name: string;

  constructor() {
    super();

    this.interval = {
      beginDate: null,
      endDate: null
    };
  }
}
```
project-list.component.ts
```
import {Component, OnInit} from '@angular/core';
import Project from '../models/project.model';
import {ProjectService} from "../services/project.service";
import {Router, NavigationExtras} from "@angular/router";

@Component({
  selector: 'dossier-project-list',
  templateUrl: './project-list.component.html',
  styleUrls: ['./project-list.component.scss']
})
export class ProjectListComponent implements OnInit {

  projects = [];

  constructor(private projectService: ProjectService,
              private router: Router) {

  }

  ngOnInit() {

    this.projectService.getAll()
      .subscribe((response: any) => {
        this.projects = response;
      });

  }
}
```

**Comment by sante85** [comment]
my angular version is 5.1.2

**Comment by sante85** [comment]
please zip a complete project for test

**Comment by Sleeper9** [comment]
Sorry, I can not post the original project, but I generated a fresh new project with Angular-CLI, added a simple service and model entity. You can run it with ng serve. It compiles without any problem, but when you open localhost:4200, the console shows the problem.

```
ng:///AppModule/AppComponent_Host.ngfactory.js:5 ERROR Error: StaticInjectorError(AppModule)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
  StaticInjectorError(Platform: core)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
    NullInjectorError: No provider for InjectionToken DocumentToken!
```

[hal-test.zip](https://github.com/masvis/angular4-hal/files/1642097/hal-test.zip)

**Comment by sante85** [comment]
simply angular version is 5.1.2 and not ^....
and typescript version is 2.4.2

and all is right

**Comment by Sleeper9** [comment]
I modified my package.json according to that, but did not help:

```
 "dependencies": {
    "@angular/animations": "5.1.2",
    "@angular/common": "5.1.2",
    "@angular/compiler": "5.1.2",
    "@angular/core": "5.1.2",
    "@angular/forms": "5.1.2",
    "@angular/http": "5.1.2",
    "@angular/platform-browser": "5.1.2",
    "@angular/platform-browser-dynamic": "5.1.2",
    "@angular/router": "5.1.2",
    "angular4-hal": "1.8.6",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.4",
    "@angular/compiler-cli": "5.1.2",
    "@angular/language-service": "5.1.2",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.9.1",
    "typescript": "2.4.2"
  }
```

My node version is v8.9.4

**Comment by sante85** [comment]
my node version is 6.11.4

**Comment by sante85** [comment]
please fork and create a pull request to support node 8

**Comment by Sleeper9** [comment]
No, it has nothing to do with node version. I tried running with v6.11.4 as you wrote, but still gives the error.
I still think that you need to fix the library packaging. Have at look at [this library starter project](https://github.com/robisim74/angular-library-starter/blob/master/package.json), I'd say you'd need to include `@angular/common` and `@angular/core` only under `"devDependencies"` section in your package.json file, and upload it this way to npm.
Because when I delete the node_modules folder from your lib, the app starts working.

**Comment by sante85** [comment]
my package

 "dependencies": {
    "@angular/cli": "^1.6.3",
    "@angular/common": "5.1.2",
    "@angular/compiler": "5.1.2",
    "@angular/compiler-cli": "5.1.2",
    "@angular/core": "5.1.2",
    "@angular/forms": "5.1.2",
    "@angular/http": "5.1.2",
    "@angular/platform-browser": "5.1.2",
    "@angular/platform-browser-dynamic": "5.1.2",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/storage": "2.1.3",
    "angular4-hal": "1.8.6",
    "lodash": "^4.17.4",
    "sass-flex-mixin": "^1.0.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0", "dependencies": {
    "@angular/cli": "^1.6.3",
    "@angular/common": "5.1.2",
    "@angular/compiler": "5.1.2",
    "@angular/compiler-cli": "5.1.2",
    "@angular/core": "5.1.2",
    "@angular/forms": "5.1.2",
    "@angular/http": "5.1.2",
    "@angular/platform-browser": "5.1.2",
    "@angular/platform-browser-dynamic": "5.1.2",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/storage": "2.1.3",
    "angular4-hal": "1.8.6",
    "lodash": "^4.17.4",
    "sass-flex-mixin": "^1.0.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.6",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18",
    "@angular/material": "5.0.4",
    "@angular/animations": "5.1.2",
    "@angular/cdk":"5.0.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.6",
    "@types/lodash": "^4.14.62",
    "typescript": "2.4.2"
  }
    "rxjs": "5.5.6",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18",
    "@angular/material": "5.0.4",
    "@angular/animations": "5.1.2",
    "@angular/cdk":"5.0.4"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.6",
    "@types/lodash": "^4.14.62",
    "typescript": "2.4.2"
  }

**Comment by sante85** [comment]
my package
[package.zip](https://github.com/masvis/angular4-hal/files/1642642/package.zip)

**Comment by Sleeper9** [comment]
Hmm, so you are using ionic... I replaced my package.json with the one you provided, and it still does not work with plain `ng serve` command.
I'll install ionic and test if it works with that.

**Comment by Sleeper9** [comment]
Any news about this?

**Comment by felixfiskare** [comment]
Using angular 6 and npm I get the same error while trying to follow the Readme

`message:"Uncaught (in promise): Error: StaticInjectorError(AppModule)[RequestEditorComponent -> TeamsService]: \n  StaticInjectorError(Platform: core)[RequestEditorComponent -> TeamsService]: \n    NullInjectorError: No provider for TeamsService!`
