### ISSUE TITLE
Please update npm package

### ISSUE THREAD

**Issue by felixfiskare** [masvis/angular4-hal#30]
First, thank you for your package.

May I ask you to release a new version on npm?
https://www.npmjs.com/package/angular4-hal has seen it's last update a month ago.

**Comment by sante85** [comment]
6.1.0 published

**Comment by felixfiskare** [comment]
thank you very much!

**Comment by felixfiskare** [comment]
Could you update again, so I can check if the new commits are fixing the "node_modules/angular4-hal/dist/src/rest.service.d.ts(28,40): error TS2314: Generic type 'ErrorObservable<T>' requires 1 type argument(s)." error?

**Comment by felixfiskare** [comment]
@sante85 ping
