### ISSUE TITLE
Angular Hal Example

### ISSUE THREAD

**Issue by mysteriousgirl7** [masvis/angular4-hal#36]
Hi, Can anyone please provide a working example. Iam trying to retrieve data for a given id  and I am using get method but it wont concatenate  id to the api url.. Not sure what Iam doing wrong. An example would help me to better understand this module.

Thanks a lot

**Comment by mysteriousgirl7** [comment]
Can someone provide API documentation for this module.Iam unable to find it.

**Comment by sante85** [comment]
Please read docs
