### ISSUE TITLE
Igrone Spring template variables in url from links

### ISSUE THREAD

**Issue by Pontiley** [masvis/angular4-hal#37]
In Spring Data Rest when we create a projection for some entity, Spring will generate for this entity in a link section additional template, for example:

```
{
   ....
   object_properties
   ....
    "_links": {
        "self": {
            "href": "http://localhost:8080/api/v1/users/1"
        },
        "user": {
            "href": "http://localhost:8080/api/v1/users/1"
        },
        "tasks": {
            "href": "http://localhost:8080/api/v1/users/1/tasks{?projection}",
            "templated": true
        }
}
```

And when in Angular we use **getRelationArray(...)** to get all tasks for the user, angular4-hal will send HTTP GET request to **http://localhost:8080/api/v1/users/1/tasks{?projection}** URL and we will get server error because this URL is not valid.

I think that we need to replace Spring template variables to an empty string when sending any HTTP requests through angular4-hal library.

**Comment by Pontiley** [comment]
I think for fix this you need to change **ResourceHelper.getProxy()** method like this:

    export class ResourceHelper {
     
       private static readonly URL_TEMPLATE_VAR_REGEXP = /{[^}]*}/g;
       private static readonly EMPTY_STRING = '';
       ...
       public static getProxy(url: string): string {
          if (!ResourceHelper.proxy_uri || ResourceHelper.proxy_uri == '')
              return ResourceHelper.removeUrlTemplateVars(url);
          return ResourceHelper.addSlash(
              ResourceHelper.removeUrlTemplateVars(url)
                  .replace(ResourceHelper.root_uri, ResourceHelper.proxy_uri));
       }

       private static removeUrlTemplateVars(url: string) {
          return url.replace(ResourceHelper.URL_TEMPLATE_VAR_REGEXP, ResourceHelper.EMPTY_STRING);
       }
       ...
   }

**Comment by fuzails** [comment]
Just picked up the same issue, will try and do a pr once I get it fixed, thanks to the hint @Pontiley

**Comment by sante85** [comment]
please make a pull request
