### ISSUE TITLE
/node_modules should not be included in the npm package

### ISSUE THREAD

**Issue by rogargon** [masvis/angular4-hal#42]
Getting conflicts when using angular4-hal 6.3.1 because the package includes the node_modules folder, which includes rxjs 6.2.2. 

This version of rxjs conflicts then with any other version above that, for instance 6.3.3 if using Angular 6.1.5+

Solved by going to ./node_modules/angular4-hal/ and removing manually the node_modules/ folder inside

**Comment by rogargon** [comment]
Checking now with last version (7.8.2) and still experiencing the same problem. The installed package includes an unnecessary ./node_modules/angular4-hal/node_modules/ that I've to manually remove if I want to run or build the project. 

Easy to solve locally but completely blocking for projects with automated builds. Solved previously having my separate version of the package at npm (https://www.npmjs.com/package/angular4-hal-aot)

**Comment by stijnvn** [comment]
I have the same problem. @sante85, can this issue be reopenend?

**Comment by cmf-cv** [comment]
Same thing here, please re-open.
