### ISSUE TITLE
Error using search: 'Observable<Observable<never> | Country>' is not assignable to type 'Observable<Country>'.

### ISSUE THREAD

**Issue by Spiff77** [masvis/angular4-hal#43]
Hello,

The Library is perfectly working to fetch everything and creating an element in the DB. I have an issue using "search" method. Here are some codes samples and additional informations.

Here is the method:
`  public findByCode(code: string): Observable<Country[]> {
    const options: any = {params: [{key: 'code', value: code}]};
    return this.search('findByCode', options);
  }`

and the error code: 

> ERROR in src/app/country.service.ts(14,5): error TS2322: Type 'Observable<Observable<never> | Country>' is not assignable to type 'Observable<Country>'.
  Type 'Observable<never> | Country' is not assignable to type 'Country'.
    Type 'Observable<never>' is not assignable to type 'Country'.
      Property '_code' is missing in type 'Observable<never>'.

Any idea? Not sure it's related to the plugin tho.

Thanks guy!

**Comment by sante85** [comment]
Country extends Resource???

**Comment by sante85** [comment]
Can you post a code example please?

**Comment by Spiff77** [comment]
Thanks for your answer,
yes it does.
Here is my country class
`
import {I18nLang} from './i18n-lang.enum';
import {ExtendedProperties} from './extended-properties';
import {City} from './city';
import {Resource} from 'angular4-hal';

export class Country extends Resource {


  constructor(
              private _code: string= '',
              private _cities: City[] = [],
              private _id: number = 0,
              private _fields: Map<I18nLang, ExtendedProperties> = new Map()
  ) {
    super();
    for (const lang of Object.keys(I18nLang)) {
      _fields.set(I18nLang[lang], new ExtendedProperties());
    }
  }

  get code(): string {
    return this._code;
  }
  set code(value: string) {
    this._code = value;
  }
  get cities(): Array<City> {
    return this._cities;
  }
  set cities(value: Array<City>) {
    this._cities = value;
  }
  get id(): number {
    return this._id;
  }

  set id(value: number) {
    this._id = value;
  }

  get fields(): Map<I18nLang, ExtendedProperties> {
    return this._fields;
  }

  set fields(value: Map<I18nLang, ExtendedProperties>) {
    this._fields = value;
  }


}

`

**Comment by Spiff77** [comment]
Thanks for your answer,
yes it does.
Here is my Country class
`import {I18nLang} from './i18n-lang.enum';
import {ExtendedProperties} from './extended-properties';
import {City} from './city';
import {Resource} from 'angular4-hal';

export class Country extends Resource {


  constructor(
              private _code: string= '',
              private _cities: City[] = [],
              private _id: number = 0,
              private _fields: Map<I18nLang, ExtendedProperties> = new Map()
  ) {
    super();
    for (const lang of Object.keys(I18nLang)) {
      _fields.set(I18nLang[lang], new ExtendedProperties());
    }
  }

  get code(): string {
    return this._code;
  }
  set code(value: string) {
    this._code = value;
  }
  get cities(): Array<City> {
    return this._cities;
  }
  set cities(value: Array<City>) {
    this._cities = value;
  }
  get id(): number {
    return this._id;
  }

  set id(value: number) {
    this._id = value;
  }

  get fields(): Map<I18nLang, ExtendedProperties> {
    return this._fields;
  }

  set fields(value: Map<I18nLang, ExtendedProperties>) {
    this._fields = value;
  }


}
`

**Comment by Spiff77** [comment]
Thanks for your answer, yes it does.
Here is my country class.
```typescript
import {I18nLang} from './i18n-lang.enum';
import {ExtendedProperties} from './extended-properties';
import {City} from './city';
import {Resource} from 'angular4-hal';

export class Country extends Resource {


  constructor(
              private _code: string= '',
              private _cities: City[] = [],
              private _id: number = 0,
              private _fields: Map<I18nLang, ExtendedProperties> = new Map()
  ) {
    super();
    for (const lang of Object.keys(I18nLang)) {
      _fields.set(I18nLang[lang], new ExtendedProperties());
    }
  }

  get code(): string {
    return this._code;
  }
  set code(value: string) {
    this._code = value;
  }
  get cities(): Array<City> {
    return this._cities;
  }
  set cities(value: Array<City>) {
    this._cities = value;
  }
  get id(): number {
    return this._id;
  }

  set id(value: number) {
    this._id = value;
  }

  get fields(): Map<I18nLang, ExtendedProperties> {
    return this._fields;
  }

  set fields(value: Map<I18nLang, ExtendedProperties>) {
    this._fields = value;
  }
}

```

**Comment by Spiff77** [comment]
I used the create inherited method instead of creating my own method.
