### ISSUE TITLE
Error: StaticInjectorError(AppModule)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]:    StaticInjectorError(Platform: core)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]:      NullInjectorError: No provider for InjectionToken DocumentToken! Error: StaticInjectorError(AppModule)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]:    StaticInjectorError(Platform: core)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]:      NullInjectorError: No provider for InjectionToken DocumentToken!

### ISSUE THREAD

**Issue by karqu** [masvis/angular4-hal#5]
I created new project from downloaded http from:
https://angular.io/guide/http#intercepting-all-requests-or-responses (downloaded example)

And I added Angular4-hal from you tutorial and I have an error if I try getting data from my server:

Error: StaticInjectorError(AppModule)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
  StaticInjectorError(Platform: core)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
    NullInjectorError: No provider for InjectionToken DocumentToken!
Error: StaticInjectorError(AppModule)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
  StaticInjectorError(Platform: core)[HttpXsrfTokenExtractor -> InjectionToken DocumentToken]: 
    NullInjectorError: No provider for InjectionToken DocumentToken!

I uploaded my project here: https://github.com/karqu/angular4-hal-example-project

**Comment by sante85** [comment]
read a guide

**Comment by karqu** [comment]
I readed this 5 times :(

Please help me or show me a project who use this library and this working...

**Comment by karqu** [comment]
Help me, please :(

**Comment by Sleeper9** [comment]
@karqu Had the same error, see #3 last comments. It looks like they are compiling and using it with ionic framework, and it bundles some angular core modules into the uploaded lib package. I'm pretty sure I provided a simple fix for that in the issue, based on my researches.

**Comment by sante85** [comment]
i have downloaded and ng serve

compile and run with no error

**Comment by sante85** [comment]
yes no errors

**Comment by Sleeper9** [comment]
@karqu I can confirm that your project **does not work**. I cloned the git repository, ran npm install, then ng serve. Firing up http://localhost:4200 gives no errors, but http://localhost:4200/teams gives the infamous error. @sante85 Please see the picture attached.

![2018-02-16 12 31 38](https://user-images.githubusercontent.com/3670641/36305794-652798f0-1315-11e8-8ef6-b45eac3f1c46.png)

**Comment by karqu** [comment]
@sante85: help us! please!

**Comment by ben33880** [comment]
i've got same pb....
the only version that works for me is : 
hal version 3.0.9 and angular 5.1.2

i cant upgrade to angular 5.2 or hal > 3.0.9 !!!!
