### ISSUE TITLE
Page Method on Service not working

### ISSUE THREAD

**Issue by richardbischof** [masvis/angular4-hal#51]
Hi there, 

I want to create a table with pagination from my Rest Resources.
Therefore I want use the _page()_ function of my service, to avoid the use of _getAll()_ function.

My service:
`export class ImageService extends RestService<Image>{...}`

My component:
```
export class ImagesComponent implements onInit {
...
constructor(private service: ImageService){...}

OnInit(){
this.service.page(0).subscribe(images => {...}
}
```

But nothing happens, when I call this.service.page(0) , no http request or anything else.

What am I missing?

Thank you all!

**Comment by sante85** [comment]
FIRST you must do a call, such as getAll

**Comment by richardbischof** [comment]
Thank you. Even after I subscribed to getAll() and calling the page method, this approach is not working. Could you give me an example or where I can find it in the documentation?

**Comment by sante85** [comment]
read readme
