### ISSUE TITLE
Extending of Resource class drops production build error

### ISSUE THREAD

**Issue by fuitattila** [masvis/angular4-hal#58]
Dear @sante85 i have a problem, with my build, please help me.

Ng version: ^7.2.4
angular4-hal version: ^7.8.1,

First of all i have a question: why is [Resource](https://github.com/masvis/angular4-hal/blob/master/src/resource.ts) class an injectable?

My production build error is:

Warning: Can't resolve all parameters for EventModel in <filePath>: (?). This will become an error in Angular v6.x

I think because of @Injectable() decorator fails the production build.

Example code to produce the error:

```
import {Resource} from 'angular4-hal';

export class EntityModel<T> extends Resource {
    readonly id?: number;

    constructor(init?: Partial<T>) {
        super();
        Object.assign(this, init);
    }
}
```

What should i do to fix this?

**Comment by sante85** [comment]
Dear user,
i not use EventModel, you even import an angular module?

**Comment by fuitattila** [comment]
Dear @sante85 

I have copied the full error message. EventModel is a class from my app, that extends your package Resource class. But your [Resource](https://github.com/masvis/angular4-hal/blob/master/src/resource.ts#L19) class uses `@Injectable()` decorator.

I think that is not useful/important there, and if you remove it, than the production build will not fail when someone extends your `Resource` class.

What do you think can I give you a PR, which removes that decorator?

**Comment by sante85** [comment]
not, because in my project is overall ok, many users uses this library and this problem is not never raised.

i extend resource without any problem.

please post your project
