### ISSUE TITLE
Errors when building 

### ISSUE THREAD

**Issue by charlottebraillie** [masvis/angular4-hal#6]
I get these errors when doing a build:
node_modules/angular4-hal/src/array-interface.ts(21,5): error TS7010: 'push', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/angular4-hal/src/resource-helper.ts(59,15): error TS2322: Type 'ResourceArray<Resource>' is not assignable to type 'ResourceArray<T>'.
  Type 'Resource' is not assignable to type 'T'.
node_modules/angular4-hal/src/resource.service.ts(70,29): error TS2304: Cannot find name 'Response'

I'm using Angular: 4.3.6

**Comment by sante85** [comment]
please post an running example
