### ISSUE TITLE
serialize / desirialize (ExternalConfigurationHandlerInterface)

### ISSUE THREAD

**Issue by andrea-daru** [masvis/angular4-hal#60]
I've found no documentation about the implementation of serialize/deserialize method of the interface ExternalConfigurationHandlerInterface.
If I follow the tutorial i can't get work the module due to wrong implementation of the interface.
Anyone experiencing the same problem?
Solutions?
Thanks in advance

**Comment by sante85** [comment]
serialize/deserialize is a feature to permit read/write external config from/to file
