### ISSUE TITLE
One to One / One to many / Many to one / Many to many

### ISSUE THREAD

**Issue by andrea-daru** [masvis/angular4-hal#61]
Hi all,
Is there a documentation on how to persist relationship with angular4-hal?
I'm unable to getting persisted a basic One to One relation.
The Backend it's developed in Spring Boot rest and if i call it directly with a rest client I can persist the relationship.
This is my first approach to Angular so maybe I'm missing something trivial.

Any help would be appreciated

**Comment by sante85** [comment]
please not open issues that there aren't.
Thank you

**Comment by andrea-daru** [comment]
This issue exists and it's related to the lack of documentation.
If you don't provide exhaustive documentation or example it will be difficult to get this module useful for other than the one that have developed it.

**Comment by sante85** [comment]
One to One relation just set sub-object in your object

class Car {
..............
private engine: Engine;
............
}

**Comment by andrea-daru** [comment]
Thanks for your help!
I've found that the problem was in my model class
