### ISSUE TITLE
Automatically fetch relations

### ISSUE THREAD

**Issue by andrea-daru** [masvis/angular4-hal#62]
Is there a way to automatically fetch the relations?
When I fetch entity that contains a related entity, the related entity it's not fetched by default.
I've to call _getRelation()/getRelationArray()_ on the owner entity.
Thank you in advance

**Comment by jefferson-lima** [comment]
I believe this would be a nice feature, I often need it too.

**Comment by sante85** [comment]
please do a pull request,
it's an hard feature

**Comment by andrea-daru** [comment]
@sante85 First let me say that's my first project in Angular.
I'm trying to _npm link angular4-hal_ (source code) in my project to develop the functionality.
After npm link I'm unable to compile due to this error:
> **ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.**

I think there are some dependencies problem between my project and angular4-hal.
Do you know how to fix it?
