### ISSUE TITLE
Need help with _embedded resources

### ISSUE THREAD

**Issue by ClementEraud** [masvis/angular4-hal#63]
Hello,
I need help on how to handle embedded resources, if we take the readme example with teams and players, then what i get from my api is something like this:

`{
_links:{
  self: { href: {'/teams/1'} }
},
_embedded: {
  players: [ list of resources ]
}
}`

from what i saw, getRelationArray is looking through links but could you give me some insights on how embedded resources are handled ?

Thanks in advance,

**Comment by sante85** [comment]
read readme
