### ISSUE TITLE
Update and Delete : Cannot read property '_links' of undefined

### ISSUE THREAD

**Issue by fbockelee** [masvis/angular4-hal#79]
Hi,

I have a functionnal REST hateoas server 
(using spring-boot-starter-parent 2.0.9.RELEASE and spring-boot-starter-hateoas)
and i can test the server using swagger

here is the response for the request 
curl -X GET "http://localhost:8082/core/menu/aa" -H "accept: application/hal+json"

	{
	  "codemenu": "aa",
	  "url": "aa",
	  "image": "aa",
	  "nom": "aa",
	  "profils": "aa",
	  "_links": {
		"self": {
		  "href": "http://localhost:8082/core/menu/aa"
		}
	  }
	}

when i try the 
curl -X DELETE "http://localhost:8082/core/menu/aa" -H "accept: application/hal+json"
with swagger, the delete is done.

I try to use angular4-hal (7.9.1) with angular 7 to access my REST HATEOAS server

The service work fine with the get,getAll,create function

but dont't work with the delete function (nor update) :

I got the following error
	ERROR TypeError: Cannot read property '_links' of undefined
	at ResourceService.push../node_modules/angular4-hal/src/resource.service.js.ResourceService.delete (resource.service.js:187)
	at MenuService.push../node_modules/angular4-hal/src/rest.service.js.RestService.delete (rest.service.js:109)
	at MenuListComponent.deleteMenu (menu-list.component.ts:103)
	at SafeSubscriber.<anonymous> (menu-list.component.ts:129)
	at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:196)
	at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:134)
	at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:77)
	at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:54)
	at Subject.push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next (Subject.js:47)
	at SafeSubscriber.<anonymous> (dialog.es5.js:429)
	
do you have an idea ?

my model

	import { Resource } from 'angular4-hal';

	export class Menu extends Resource {
		codemenu: string; // Wrapper Type : String
		url: string; // Wrapper Type : String
		image: string; // Wrapper Type : String
		nom: string; // Wrapper Type : String
		profils: string; // Wrapper Type : String
	}

my service

	import { RestService } from 'angular4-hal';
	import { Injectable, Injector } from '@angular/core';
	import { Menu } from '../menu.model';

	@Injectable()
	export class MenuService extends RestService<Menu>  {

		/**
		 * Constructor
		 * @param _http Http
		 * @param _configuration Configuration
		 */
		constructor(injector: Injector) {
			super(Menu, 'menu', injector);
		}

	}

the call to getAll (which work) 

	 getAllMenus = (): void => {
		this._menuService.getAll({ notPaged: true }).subscribe(
		  (data: Menu[]) => {
			this.listOfMenus = data;
			this.setPage(1);
		  },
		  error => {
			this._notificationService.error(
			  'Error',
			  'An error occured when trying to reach the server');
		});
	  }

the call to delete (which don't work):

	  deleteMenu = (codemenu: string): void => {
		// Call the get service
		this._menuService.get(codemenu).subscribe(
		  (menu: Menu) => {
			this.menu = menu;
			//this.form = this._formBuilder.group(this.getNewForm(this.menu));
		  },
		  error => {
			if (error.status === this.NOT_FOUND_ERROR) {
			  this._notificationService.error(error.statusText, 'Entity not found in database');
			} else if (error.status === this.INTERNAL_SERVER_ERROR) {
			  this._notificationService.error(error.statusText, error.json());
			} else {
			  this._notificationService.error('Error', 'An error occured when trying to reach the server');
			}
		  });

		// Call the delete service
		// the above get is OK
		// I try the delete(codemenu) but the function need a Menu
		//		
		this._menuService.delete(this.menu).subscribe(
		  result => {
			// Notify Menu list to refresh
			EmitterService.get(this.listId).emit(result);

			this._notificationService.success(
			  'Deleted',
			  `The menu entry with the id='${codemenu}' was deleted successfuly`);
		  },
		  error => {
			this._notificationService.error(
			  'Error',
			  'An error occured when trying to reach the server');
		  });
	  }
  
Do you have an advice of what is wrong ?

**Comment by fbockelee** [comment]
the entity in parameter to delete was not correct due to callback;
 
solved by adding promise
thx a lot for your project !!

	deleteMenu = (codemenu: string): void => {
	// Call the get service
	console.log('before get :' + codemenu);

	let promise = new Promise((resolve, reject) => {
	  this._menuService.get(codemenu).subscribe(
		(menu: Menu) => {
		  this.menu = menu;
		  console.log('get :'+ this.menu.codemenu + ' ' + this.menu.nom);
		  resolve('done');
		  //this.form = this._formBuilder.group(this.getNewForm(this.menu));
		},
		error => {
		  if (error.status === this.NOT_FOUND_ERROR) {
			this._notificationService.error(error.statusText, 'Entity not found in database');
			reject('error');
		  } else if (error.status === this.INTERNAL_SERVER_ERROR) {
			this._notificationService.error(error.statusText, error.json());
			reject('error');
		  } else {
			this._notificationService.error('Error', 'An error occured when trying to reach the server');
			reject('error');
		  }
		})
		;
	})
	.then(() => {
	  // Call the delete service
	  this._menuService.delete(this.menu).subscribe(
	  result => {
		// Notify Menu list to refresh
		EmitterService.get(this.listId).emit(result);

		this._notificationService.success(
		  'Deleted',
		  `The menu entry with the id='${codemenu}' was deleted successfuly`);
	  },
	  error => {
		this._notificationService.error(
		  'Error',
		  'An error occured when trying to reach the server');
	  });
	});

	}

**Comment by sante85** [comment]
Please pull request

Il Mer 12 Feb 2020, 13:15 fbockelee <notifications@github.com> ha scritto:
