### ISSUE TITLE
Accessing multiple HATEOAS/HAL/SDREST APIs

### ISSUE THREAD

**Issue by loesak** [masvis/angular4-hal#8]
Not sure if this is how to contact about questions or feature requests so I apologize in advance if this not the correct place.

i've been looking for an angular library for interacting with Spring Data REST HAL APIs. Yours seems the most complete and most downloaded. However, skimming the documentation, I'm seeing some things that may prevent me from using this library, but maybe these are more my lack of understaing with the library and or angular (fairly new to angular).

The first thing i noticed was that it seems to only work with a single SD REST resource. For my need, i've created a set of microservices of which a bunch of them are SD REST resources that live at different base URL's (either their own or more likely being a ZUUL proxy). Is there any way connect to multiple with this library?

I have others but wondering if you prefer them as different issues.

Thank you for putting this project together and for your response.

**Comment by sante85** [comment]
no in roadmap
