### ISSUE TITLE
Npm 3.2.0 and github 3.2.0 missmatch

### ISSUE THREAD

**Issue by Otakug3** [masvis/angular4-hal#9]
Hi, I updated to 3.2.0 and when i do the npm install everything stopped work. I see that the folder src isn't there anymore and the dist/ folder neither.

Delete /dist it's ok to me because npm generates everytime but i think that you added src to .npmignore wrongly and it's not been delivered anymore via npm.

I did some tests with my forked project and added src manually but when i try to do a ng build --prod in my project it fails with:

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'AngularHalModule' was called.

Do you know what's happening?

**Comment by sante85** [comment]
resolved
